# Generated by Django 4.0.1 on 2022-02-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0002_loadimage_image_alter_loadimage_url_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='loadimage',
            name='url_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/'),
        ),
    ]
